/**
 * Copyright IBM Corp. 2021, 2026
 * SPDX-License-Identifier: MPL-2.0
 */

// generated by cdktf get
Object.defineProperty(exports, 'dataHttp', { get: function () { return require('./data-http'); } });
Object.defineProperty(exports, 'provider', { get: function () { return require('./provider'); } });

